map_ids = {
    1: {
        1: {
            1: {
                "address": "he1_01",
                "description": "Lineland Road, map with Bestovious's house",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "he1_02",
                "description": "Lineland Road, map with the hills in the background",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "he1_03",
                "description": "Lineland Road, underground map with a treasure chest",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "he1_04",
                "description": "Lineland Road, map with brown blocks stairs",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "he1_05",
                "description": "Lineland Road, map with Mega Star and Star Block",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "he1_06",
                "description": "Lineland Road, inside Bestovius's house",
                "sequence": None,
                "needs": "",
            },
        },
        2: {
            1: {
                "address": "he2_01",
                "description": "Mount Lineland, map with blue switch",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "he2_02",
                "description": "Mount Lineland, map with Spiny Tromps",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "he2_03",
                "description": "Mount Lineland, map with village",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "he2_04",
                "description": "Mount Lineland, inside Red's house",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "he2_05",
                "description": "Mount Lineland, inside Green's house",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "he2_06",
                "description": "Mount Lineland, underground map with Thwomps",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "he2_07",
                "description": "Mount Lineland, Thoreau room",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "he2_08",
                "description": "Mount Lineland, underground room with coins",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "he2_09",
                "description": "Mount Lineland, map with 2 star door near each other",
                "sequence": None,
                "needs": "",
            },
        },
        3: {
            1: {
                "address": "he3_01",
                "description": "Yold Desert, map with the red palm tree",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "he3_02",
                "description": "Yold Desert, map with the rock that has an arrow above it",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "he3_03",
                "description": "Yold Desert, map with the save block",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "he3_04",
                "description": "Yold Desert, O'Chunks fight map",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "he3_05",
                "description": "Yold Desert, underground map with ? blocks",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "he3_06",
                "description": "Yold Desert, map with yellow moving platforms",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "he3_07",
                "description": "Yold Desert, map with blue stone",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "he3_08",
                "description": "Yold Desert, map with blue pedestal Star Block",
                "sequence": None,
                "needs": "",
            },
        },
        4: {
            1: {
                "address": "he4_01",
                "description": "Yold Ruins, first map",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "he4_02",
                "description": "Yold Ruins, map with a fire bar and three moving sand pits",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "he4_03",
                "description": "Yold Ruins, map with five fire bars and three doors",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "he4_04",
                "description": "Yold Ruins, map with two Spiky Tromp and a treasure chest",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "he4_05",
                "description": "Yold Ruins, map with a save block and a large moving sand pit",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "he4_06",
                "description": "Yold Ruins, map with a blue switch and an enemy pipe",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "he4_07",
                "description": "Yold Ruins, map with three firebars, two doors and a frame of brown blocks",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "he4_08",
                "description": "Yold Ruins, map with the Spiky Tromps cages",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "he4_09",
                "description": "Yold Ruins, map with a save block near a pipe",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "he4_10",
                "description": "Yold Ruins, Fracktail fight map",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "he4_11",
                "description": "Yold Ruins, map with Star Block",
                "sequence": None,
                "needs": "",
            },
            12: {
                "address": "he4_12",
                "description": "Yold Ruins, map with hidden a hidden platform underneath a door",
                "sequence": None,
                "needs": "",
            },
        },
    },
    2: {
        1: {
            1: {
                "address": "mi1_01",
                "description": "Gloam Valley, first map",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "mi1_02",
                "description": "Gloam Valley, map with three floors and two Spiky Goombas",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "mi1_03",
                "description": "Gloam Valley, map with three floors and two Shlurps",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "mi1_04",
                "description": "Gloam Valley, map with Star Block",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "mi1_05",
                "description": "Gloam Valley, underground map with a treasure chest and some Squigs",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "mi1_06",
                "description": "Gloam Valley, map with an invisible blue switch block",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "mi1_07",
                "description": "Gloam Valley, map of Boomer chest",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "mi1_08",
                "description": "Gloam Valley, map with wind turbines in the background",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "mi1_09",
                "description": "Gloam Valley, map with Lock (an npc)",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "mi1_10",
                "description": "Gloam Valley, map with six doors",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "mi1_11",
                "description": "Gloam Valley, map with Mega Star",
                "sequence": None,
                "needs": "",
            },
        },
        2: {
            1: {
                "address": "mi2_01",
                "description": "Merlee's Mansion, entrance of the mansion",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "mi2_02",
                "description": "Merlee's Mansion, map with small crystal ball",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "mi2_03",
                "description": "Merlee's Mansion, map with six doors",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "mi2_04",
                "description": "Merlee's Mansion, map with a suspended Mushroom",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "mi2_05",
                "description": "Merlee's Mansion, map with a trail of coins",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "mi2_06",
                "description": "Merlee's Mansion, map with spikes ceiling",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "mi2_07",
                "description": "Merlee's Mansion, map with a Mushrooms on the floor attached to a chain",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "mi2_08",
                "description": "Merlee's Mansion, map with Star Block",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "mi2_09",
                "description": "Merlee's Mansion, underground map with a Shlurp",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "mi2_10",
                "description": "Merlee's Mansion, underground map with two Swoopers",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "mi2_11",
                "description": "Merlee's Mansion, underground map with three Boos",
                "sequence": None,
                "needs": "",
            },
        },
        3: {
            1: {
                "address": "mi3_01",
                "description": "Merlee's Mansion, main map",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "mi3_02",
                "description": "Merlee's Mansion, map with the npc who gives you the safe code",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "mi3_03",
                "description": "Merlee's Mansion, map with the spinning wheel",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "mi3_04",
                "description": "Merlee's Mansion, map with the electrical blocks",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "mi3_05",
                "description": "Merlee's Mansion, map with an infinite Mushroom blocks",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "mi3_06",
                "description": "Merlee's Mansion, map with the Star Block",
                "sequence": None,
                "needs": "",
            },
        },
        4: {
            1: {
                "address": "mi4_01",
                "description": "Merlee's Basement, first map",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "mi4_02",
                "description": "Merlee's Basement, Room 01",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "mi4_03",
                "description": "Merlee's Basement, Room 02",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "mi4_04",
                "description": "Merlee's Basement, Room 03",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "mi4_05",
                "description": "Merlee's Basement, Room 04",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "mi4_06",
                "description": "Merlee's Basement, map with a red background wall and two floors",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "mi4_07",
                "description": "Merlee's Basement, Room 06",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "mi4_08",
                "description": "Merlee's Basement, Room 07",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "mi4_09",
                "description": "Merlee's Basement, map with a narrow hole on the floor",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "mi4_10",
                "description": "Merlee's Basement, Room 08",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "mi4_11",
                "description": "Merlee's Basement, Room 09",
                "sequence": None,
                "needs": "",
            },
            12: {
                "address": "mi4_12",
                "description": "Merlee's Basement, map with two bathroom doors and a save block",
                "sequence": None,
                "needs": "",
            },
            13: {
                "address": "mi4_13",
                "description": "Merlee's Basement, mens bathroom",
                "sequence": None,
                "needs": "",
            },
            14: {
                "address": "mi4_14",
                "description": "Merlee's Basement, women bathroom (with the Star Block)",
                "sequence": None,
                "needs": "",
            },
            15: {
                "address": "mi4_15",
                "description": "Merlee's Basement, map with an Atomic Boo",
                "sequence": None,
                "needs": "",
            },
        },
    },
    3: {
        1: {
            1: {
                "address": "ta1_01",
                "description": "The Bitlands, map with two red pipes",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "ta1_02",
                "description": "The Bitlands, map with Mega Star",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "ta1_03",
                "description": "The Bitlands, retro underground map",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "ta1_04",
                "description": "The Bitlands, map with Star Block",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "ta1_05",
                "description": "The Bitlands, underground map with two pipes, a treasure chest and a Blomeba",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "ta1_06",
                "description": "The Bitlands, retro underground map with brick blocks and a pipe",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "ta1_07",
                "description": "The Bitlands, retro underground map with a brick block and a pyramid with a treasure chest behind it",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "ta1_08",
                "description": "The Bitlands, retro underground map with five ? blocks",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "ta1_09",
                "description": "The Bitlands, map with Mega Koopa",
                "sequence": None,
                "needs": "",
            },
        },
        2: {
            1: {
                "address": "ta2_01",
                "description": "The Tile Pool, first map",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "ta2_02",
                "description": "The Tile Pool, map with Big Bloopers's tentacles",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "ta2_03",
                "description": "The Tile Pool, map with two Spiky Goombas above the surface",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "ta2_04",
                "description": "The Tile Pool, map with Thudley chest",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "ta2_05",
                "description": "The Tile Pool, Big Blooper fight map",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "ta2_06",
                "description": "The Tile Pool, map with a Star Block",
                "sequence": None,
                "needs": "",
            },
        },
        3: {
            1: {
                "address": "ta3_01",
                "description": "The Dotwood Tree, first map",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "ta3_02",
                "description": "The Dotwood Tree, main map inside the tree with a save block",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "ta3_03",
                "description": "The Dotwood Tree, map with red winds",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "ta3_04",
                "description": "The Dotwood Tree, map with the Star Block",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "ta3_05",
                "description": "The Dotwood Tree, map inside the tree with a yellow pipe and a platform",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "ta3_06",
                "description": "The Dotwood Tree, map inside the tree with spikes on the floor",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "ta3_07",
                "description": "The Dotwood Tree, map with two Chain Chomp and a treasure chest",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "ta3_08",
                "description": "The Dotwood Tree, map inside the tree with a moving platform and spikes on a wall",
                "sequence": None,
                "needs": "",
            },
        },
        4: {
            1: {
                "address": "ta4_01",
                "description": "Fort Francis, fort entrance",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "ta4_02",
                "description": "Fort Francis, underground map with a treasure chest",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "ta4_03",
                "description": "Fort Francis, map with a saveblock",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "ta4_04",
                "description": "Fort Francis, map with the cat door",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "ta4_05",
                "description": "Fort Francis, map that is an access to the second floor",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "ta4_06",
                "description": "Fort Francis, map with the two doors that hangs on the wall",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "ta4_07",
                "description": "Fort Francis, map that is an access to the third floor",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "ta4_08",
                "description": "Fort Francis, map that is outside the castle with a bridge",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "ta4_09",
                "description": "Fort Francis, map with the right room door",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "ta4_10",
                "description": "Fort Francis, map with the right room treasure chest",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "ta4_11",
                "description": "Fort Francis, map with the left room elevator",
                "sequence": None,
                "needs": "",
            },
            12: {
                "address": "ta4_12",
                "description": "Fort Francis, map with Carrie",
                "sequence": None,
                "needs": "",
            },
            13: {
                "address": "ta4_13",
                "description": "Fort Francis, map with the Star Block",
                "sequence": None,
                "needs": "",
            },
            14: {
                "address": "ta4_14",
                "description": "Fort Francis, map with spikes on the floor",
                "sequence": None,
                "needs": "",
            },
            15: {
                "address": "ta4_15",
                "description": "Fort Francis, map with a red button and a Chain Chomp",
                "sequence": None,
                "needs": "",
            },
        },
    },
    4: {
        1: {
            1: {
                "address": "sp1_01",
                "description": "Outer Space, first map",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "sp1_02",
                "description": "Outer Space, map with enemies, a black hole and a save block",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "sp1_03",
                "description": "Outer Space, map with enemies and two black holes on the right",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "sp1_04",
                "description": "Outer Space, map with enemies and two black holes on the left",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "sp1_05",
                "description": "Outer Space, map with two black holes and Warpids",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "sp1_06",
                "description": "Outer Space, map with Star Block",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "sp1_07",
                "description": "Outer Space, secret map with coins and a ? block",
                "sequence": None,
                "needs": "",
            },
        },
        2: {
            1: {
                "address": "sp2_01",
                "description": "Planet Blobule, map with bathroom",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "sp2_02",
                "description": "Planet Blobule, map with Star Block",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "sp2_03",
                "description": "Planet Blobule, map with a save block nearby a star door",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "sp2_04",
                "description": "Planet Blobule, map with Hooligons and 2 ? blocks",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "sp2_05",
                "description": "Planet Blobule, map with green and purple door on the right",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "sp2_06",
                "description": "Planet Blobule, map with Blollop (yellow Blobule)",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "sp2_07",
                "description": "Planet Blobule, map with Blarfle (blue Blobule)",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "sp2_08",
                "description": "Planet Blobule, map with Blappy (purple Blobule)",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "sp2_09",
                "description": "Planet Blobule, secret map with blue flowers in the background and coins",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "sp2_10",
                "description": "Planet Blobule, map with Mega Star",
                "sequence": None,
                "needs": "",
            },
        },
        3: {
            1: {
                "address": "sp3_01",
                "description": "Outer Limits, first map",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "sp3_02",
                "description": "Outer Limits, map with two green giant doors",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "sp3_03",
                "description": "Outer Limits, map with Star Block",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "sp3_04",
                "description": "Outer Limits, map with multiple black holes",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "sp3_05",
                "description": "Outer Limits, map with the Twinkle Mart",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "sp3_06",
                "description": "Outer Limits, map with two black holes and a save block",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "sp3_07",
                "description": "Outer Limits, map with a black holes and coins",
                "sequence": None,
                "needs": "",
            },
        },
        4: {
            1: {
                "address": "sp4_01",
                "description": "The Whoa Zone, first map",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "sp4_02",
                "description": "The Whoa Zone, map with three doors and one of them is hidden",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "sp4_03",
                "description": "The Whoa Zone, map with three hidden stairs",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "sp4_04",
                "description": "The Whoa Zone, map with four doors and two of them are hidden",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "sp4_05",
                "description": "The Whoa Zone, map with a treasure chest and a Barribad",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "sp4_06",
                "description": "The Whoa Zone, map that is walked sideways with doors",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "sp4_07",
                "description": "The Whoa Zone, map with two doors, a pipe and an upside down treasure chest",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "sp4_08",
                "description": "The Whoa Zone, map with and a staircase, one of the doors is upside down",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "sp4_09",
                "description": "UNUSED, The Whoa Zone, map with grey blocks and an upside down treasure chest containing Piccolo's card",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "sp4_10",
                "description": "The Whoa Zone, map that is walked on all four sides",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "sp4_11",
                "description": "The Whoa Zone, map with a save block that has a door upside down",
                "sequence": None,
                "needs": "",
            },
            12: {
                "address": "sp4_12",
                "description": "The Whoa Zone, map with five doors that is walked on three sides and has a treasure chest",
                "sequence": None,
                "needs": "",
            },
            13: {
                "address": "sp4_13",
                "description": "The Whoa Zone, Mr. L fight map",
                "sequence": None,
                "needs": "",
            },
            14: {
                "address": "sp4_14",
                "description": "The Whoa Zone, map with the Star Block",
                "sequence": None,
                "needs": "",
            },
            15: {
                "address": "sp4_15",
                "description": "The Whoa Zone, map with a pipe upside down and a coin block",
                "sequence": None,
                "needs": "",
            },
            16: {
                "address": "sp4_16",
                "description": "The Whoa Zone, map with two doors that has two flipping blocks",
                "sequence": None,
                "needs": "",
            },
            17: {
                "address": "sp4_17",
                "description": "The Whoa Zone, Brobot fight map (loads the Brobot encounter cutscene upon loading, and revert the sequence to 171)",
                "sequence": None,
                "needs": "",
            },
        },
    },
    5: {
        1: {
            1: {
                "address": "gn1_01",
                "description": "Downtown of Crag, map with the village",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "gn1_02",
                "description": "Downtown of Crag, map with the short blocks code",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "gn1_03",
                "description": "Downtown of Crag, map with the long blocks code and the Star Block",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "gn1_04",
                "description": "Downtown of Crag, map with the cave background and the Shlorps",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "gn1_05",
                "description": "Downtown of Crag, underground map with coins underwater",
                "sequence": None,
                "needs": "",
            },
        },
        2: {
            1: {
                "address": "gn2_01",
                "description": "Gap of Crag, map with the Water Tablet chest",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "gn2_02",
                "description": "Gap of Crag, map with the three stones",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "gn2_03",
                "description": "Gap of Crag, map with the Stone Tablet",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "gn2_04",
                "description": "Gap of Crag, map with the Fire Tablet",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "gn2_05",
                "description": "Gap of Crag, map with the Star Block",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "gn2_06",
                "description": "Gap of Crag, map with the Tablet order written in the background",
                "sequence": None,
                "needs": "",
            },
        },
        3: {
            1: {
                "address": "gn3_01",
                "description": "Floro Caverns, map with Flint Cragley",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "gn3_02",
                "description": "UNUSED Floro Caverns,, map with two pipes, two doors, a save block and some enemies",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "gn3_03",
                "description": "Floro Caverns, map with a save block",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "gn3_04",
                "description": "Floro Caverns, small room",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "gn3_05",
                "description": "Floro Caverns, secret map with treasure chest",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "gn3_06",
                "description": "Floro Caverns, map with the first crew member",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "gn3_07",
                "description": "Floro Caverns, very small room",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "gn3_08",
                "description": "Floro Caverns, map with the second crew member",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "gn3_09",
                "description": "Floro Caverns, map with the Star Block",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "gn3_10",
                "description": "Floro Caverns, secret map with a block",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "gn3_11",
                "description": "Floro Caverns, first minecart track",
                "sequence": None,
                "needs": "",
            },
            12: {
                "address": "gn3_12",
                "description": "Floro Caverns, second minecart track",
                "sequence": None,
                "needs": "",
            },
            13: {
                "address": "gn3_13",
                "description": "Floro Caverns, third minecart track",
                "sequence": None,
                "needs": "",
            },
            14: {
                "address": "gn3_14",
                "description": "Floro Caverns, map with Mega Star",
                "sequence": None,
                "needs": "",
            },
            15: {
                "address": "gn3_15",
                "description": "Floro Caverns, map with long corridor",
                "sequence": None,
                "needs": "",
            },
            16: {
                "address": "gn3_16",
                "description": "Floro Caverns, map with coins",
                "sequence": None,
                "needs": "",
            },
        },
        4: {
            1: {
                "address": "gn4_01",
                "description": "Floro Caverns, first map (with iron door on the right)",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "gn4_02",
                "description": "Floro Caverns, map with a save block near an iron door",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "gn4_03",
                "description": "Floro Caverns, Dottie room",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "gn4_04",
                "description": "Floro Caverns, map with two pipes and a door",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "gn4_05",
                "description": "Floro Caverns, map with Reversya Cursya, a pipe and two doors",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "gn4_06",
                "description": "Floro Caverns, map with Spike Top, a pipe and a door",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "gn4_07",
                "description": "Floro Caverns, map with a skull on the wall",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "gn4_08",
                "description": "Floro Caverns, map with Heavy Cursya, a pipe and two doors",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "gn4_09",
                "description": "Floro Caverns, map with a Blomeba a pipe and a door",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "gn4_10",
                "description": "Floro Caverns, map with two iron doors and a card key slot",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "gn4_11",
                "description": "Floro Caverns, map with an iron door, two pipe and a ? block",
                "sequence": None,
                "needs": "",
            },
            12: {
                "address": "gn4_12",
                "description": "Floro Caverns, map with the Cragnons cages and the Cursya",
                "sequence": None,
                "needs": "",
            },
            13: {
                "address": "gn4_13",
                "description": "Floro Caverns, map with two pipes (the room where you meet Dimentio)",
                "sequence": None,
                "needs": "",
            },
            14: {
                "address": "gn4_14",
                "description": "Floro Caverns, map with the scanner",
                "sequence": None,
                "needs": "",
            },
            15: {
                "address": "gn4_15",
                "description": "Floro Caverns, map with the Floro Queens portraits",
                "sequence": None,
                "needs": "",
            },
            16: {
                "address": "gn4_16",
                "description": "Floro Caverns, map with the Star Block",
                "sequence": None,
                "needs": "",
            },
            17: {
                "address": "gn4_17",
                "description": "Floro Caverns, secret map with a mini pipe and ? blocks",
                "sequence": None,
                "needs": "",
            },
        },
    },
    6: {
        1: {
            1: {
                "address": "wa1_01",
                "description": "Sammer's Kingdom, first map",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "wa1_02",
                "description": "Sammer's Kingdom, map of the 1st gate",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "wa1_03",
                "description": "Sammer's Kingdom, map of the 2nd gate",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "wa1_04",
                "description": "Sammer's Kingdom, map of the 3th gate",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "wa1_05",
                "description": "Sammer's Kingdom, map of the 4th gate",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "wa1_06",
                "description": "Sammer's Kingdom, map of the 5th gate",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "wa1_07",
                "description": "Sammer's Kingdom, map of the 6th gate",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "wa1_08",
                "description": "Sammer's Kingdom, map of the 7th gate",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "wa1_09",
                "description": "Sammer's Kingdom, map of the 8th gate",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "wa1_10",
                "description": "Sammer's Kingdom, map of the 9th gate",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "wa1_11",
                "description": "Sammer's Kingdom, map of the 10th gate",
                "sequence": None,
                "needs": "",
            },
            12: {
                "address": "wa1_12",
                "description": "Sammer's Kingdom, map of the 11th gate",
                "sequence": None,
                "needs": "",
            },
            13: {
                "address": "wa1_13",
                "description": "Sammer's Kingdom, map of the 12th gate",
                "sequence": None,
                "needs": "",
            },
            14: {
                "address": "wa1_14",
                "description": "Sammer's Kingdom, map of the 13th gate",
                "sequence": None,
                "needs": "",
            },
            15: {
                "address": "wa1_15",
                "description": "Sammer's Kingdom, map of the 14th gate",
                "sequence": None,
                "needs": "",
            },
            16: {
                "address": "wa1_16",
                "description": "Sammer's Kingdom, map of the 15th gate",
                "sequence": None,
                "needs": "",
            },
            17: {
                "address": "wa1_17",
                "description": "Sammer's Kingdom, map of the 16th gate",
                "sequence": None,
                "needs": "",
            },
            18: {
                "address": "wa1_18",
                "description": "Sammer's Kingdom, map of the 17th gate",
                "sequence": None,
                "needs": "",
            },
            19: {
                "address": "wa1_19",
                "description": "Sammer's Kingdom, map of the 18th gate",
                "sequence": None,
                "needs": "",
            },
            20: {
                "address": "wa1_20",
                "description": "Sammer's Kingdom, map of the 19th gate",
                "sequence": None,
                "needs": "",
            },
            21: {
                "address": "wa1_21",
                "description": "Sammer's Kingdom, map of the 20th gate",
                "sequence": None,
                "needs": "",
            },
            22: {
                "address": "wa1_22",
                "description": "Sammer's Kingdom, map of the 21th gate",
                "sequence": None,
                "needs": "",
            },
            23: {
                "address": "wa1_23",
                "description": "Sammer's Kingdom, map of the 22th gate",
                "sequence": None,
                "needs": "",
            },
            24: {
                "address": "wa1_24",
                "description": "Sammer's Kingdom, map of the 23th gate",
                "sequence": None,
                "needs": "",
            },
            25: {
                "address": "wa1_25",
                "description": "Sammer's Kingdom, map of the 24th gate",
                "sequence": None,
                "needs": "",
            },
            26: {
                "address": "wa1_26",
                "description": "Sammer's Kingdom, map of the 25th gate (with the Star Block)",
                "sequence": None,
                "needs": "",
            },
            27: {
                "address": "wa1_27",
                "description": "Sammer's Kingdom, map of the World of Nothing",
                "sequence": None,
                "needs": "",
            },
        },
        2: {
            1: {
                "address": "wa2_01",
                "description": "Sammer's Early Duels, map of the 26th gate",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "wa2_02",
                "description": "Sammer's Early Duels, map of the 27th gate",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "wa2_03",
                "description": "Sammer's Early Duels, map of the 28th gate",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "wa2_04",
                "description": "Sammer's Early Duels, map of the 29th gate",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "wa2_05",
                "description": "Sammer's Early Duels, map of the 30th gate",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "wa2_06",
                "description": "Sammer's Early Duels, map of the 31th gate",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "wa2_07",
                "description": "Sammer's Early Duels, map of the 32th gate",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "wa2_08",
                "description": "Sammer's Early Duels, map of the 33th gate",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "wa2_09",
                "description": "Sammer's Early Duels, map of the 34th gate",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "wa2_10",
                "description": "Sammer's Early Duels, map of the 35th gate",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "wa2_11",
                "description": "Sammer's Early Duels, map of the 36th gate",
                "sequence": None,
                "needs": "",
            },
            12: {
                "address": "wa2_12",
                "description": "Sammer's Early Duels, map of the 37th gate",
                "sequence": None,
                "needs": "",
            },
            13: {
                "address": "wa2_13",
                "description": "Sammer's Early Duels, map of the 38th gate",
                "sequence": None,
                "needs": "",
            },
            14: {
                "address": "wa2_14",
                "description": "Sammer's Early Duels, map of the 39th gate",
                "sequence": None,
                "needs": "",
            },
            15: {
                "address": "wa2_15",
                "description": "Sammer's Early Duels, map of the 40th gate",
                "sequence": None,
                "needs": "",
            },
            16: {
                "address": "wa2_16",
                "description": "Sammer's Early Duels, map of the 41th gate",
                "sequence": None,
                "needs": "",
            },
            17: {
                "address": "wa2_17",
                "description": "Sammer's Early Duels, map of the 42th gate",
                "sequence": None,
                "needs": "",
            },
            18: {
                "address": "wa2_18",
                "description": "Sammer's Early Duels, map of the 43th gate",
                "sequence": None,
                "needs": "",
            },
            19: {
                "address": "wa2_19",
                "description": "Sammer's Early Duels, map of the 44th gate",
                "sequence": None,
                "needs": "",
            },
            20: {
                "address": "wa2_20",
                "description": "Sammer's Early Duels, map of the 45th gate",
                "sequence": None,
                "needs": "",
            },
            21: {
                "address": "wa2_21",
                "description": "Sammer's Early Duels, map of the 46th gate",
                "sequence": None,
                "needs": "",
            },
            22: {
                "address": "wa2_22",
                "description": "Sammer's Early Duels, map of the 47th gate",
                "sequence": None,
                "needs": "",
            },
            23: {
                "address": "wa2_23",
                "description": "Sammer's Early Duels, map of the 48th gate",
                "sequence": None,
                "needs": "",
            },
            24: {
                "address": "wa2_24",
                "description": "Sammer's Early Duels, map of the 49th gate",
                "sequence": None,
                "needs": "",
            },
            25: {
                "address": "wa2_25",
                "description": "Sammer's Early Duels, map of the 50th gate (with the Star Block)",
                "sequence": None,
                "needs": "",
            },
        },
        3: {
            1: {
                "address": "wa3_01",
                "description": "Sammer's Proving Grounds, map of the 51th gate",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "wa3_02",
                "description": "Sammer's Proving Grounds, map of the 52th gate",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "wa3_03",
                "description": "Sammer's Proving Grounds, map of the 53th gate",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "wa3_04",
                "description": "Sammer's Proving Grounds, map of the 54th gate",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "wa3_05",
                "description": "Sammer's Proving Grounds, map of the 55th gate",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "wa3_06",
                "description": "Sammer's Proving Grounds, map of the 56th gate",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "wa3_07",
                "description": "Sammer's Proving Grounds, map of the 57th gate",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "wa3_08",
                "description": "Sammer's Proving Grounds, map of the 58th gate",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "wa3_09",
                "description": "Sammer's Proving Grounds, map of the 59th gate",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "wa3_10",
                "description": "Sammer's Proving Grounds, map of the 60th gate",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "wa3_11",
                "description": "Sammer's Proving Grounds, map of the 61th gate",
                "sequence": None,
                "needs": "",
            },
            12: {
                "address": "wa3_12",
                "description": "Sammer's Proving Grounds, map of the 62th gate",
                "sequence": None,
                "needs": "",
            },
            13: {
                "address": "wa3_13",
                "description": "Sammer's Proving Grounds, map of the 63th gate",
                "sequence": None,
                "needs": "",
            },
            14: {
                "address": "wa3_14",
                "description": "Sammer's Proving Grounds, map of the 64th gate",
                "sequence": None,
                "needs": "",
            },
            15: {
                "address": "wa3_15",
                "description": "Sammer's Proving Grounds, map of the 65th gate",
                "sequence": None,
                "needs": "",
            },
            16: {
                "address": "wa3_16",
                "description": "Sammer's Proving Grounds, map of the 66th gate",
                "sequence": None,
                "needs": "",
            },
            17: {
                "address": "wa3_17",
                "description": "Sammer's Proving Grounds, map of the 67th gate",
                "sequence": None,
                "needs": "",
            },
            18: {
                "address": "wa3_18",
                "description": "Sammer's Proving Grounds, map of the 68th gate",
                "sequence": None,
                "needs": "",
            },
            19: {
                "address": "wa3_19",
                "description": "Sammer's Proving Grounds, map of the 69th gate",
                "sequence": None,
                "needs": "",
            },
            20: {
                "address": "wa3_20",
                "description": "Sammer's Proving Grounds, map of the 70th gate",
                "sequence": None,
                "needs": "",
            },
            21: {
                "address": "wa3_21",
                "description": "Sammer's Proving Grounds, map of the 71th gate",
                "sequence": None,
                "needs": "",
            },
            22: {
                "address": "wa3_22",
                "description": "Sammer's Proving Grounds, map of the 72th gate",
                "sequence": None,
                "needs": "",
            },
            23: {
                "address": "wa3_23",
                "description": "Sammer's Proving Grounds, map of the 73th gate",
                "sequence": None,
                "needs": "",
            },
            24: {
                "address": "wa3_24",
                "description": "Sammer's Proving Grounds, map of the 74th gate",
                "sequence": None,
                "needs": "",
            },
            25: {
                "address": "wa3_25",
                "description": "Sammer's Proving Grounds, map of the 75th gate (with the Star Block)",
                "sequence": None,
                "needs": "",
            },
        },
        4: {
            1: {
                "address": "wa4_01",
                "description": "Sammer's Endgame, map of the 76th gate",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "wa4_02",
                "description": "Sammer's Endgame, map of the 77th gate",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "wa4_03",
                "description": "Sammer's Endgame, map of the 78th gate",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "wa4_04",
                "description": "Sammer's Endgame, map of the 79th gate",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "wa4_05",
                "description": "Sammer's Endgame, map of the 80th gate",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "wa4_06",
                "description": "Sammer's Endgame, map of the 81th gate",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "wa4_07",
                "description": "Sammer's Endgame, map of the 82th gate",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "wa4_08",
                "description": "Sammer's Endgame, map of the 83th gate",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "wa4_09",
                "description": "Sammer's Endgame, map of the 84th gate",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "wa4_10",
                "description": "Sammer's Endgame, map of the 85th gate",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "wa4_11",
                "description": "Sammer's Endgame, map of the 86th gate",
                "sequence": None,
                "needs": "",
            },
            12: {
                "address": "wa4_12",
                "description": "Sammer's Endgame, map of the 87th gate",
                "sequence": None,
                "needs": "",
            },
            13: {
                "address": "wa4_13",
                "description": "Sammer's Endgame, map of the 88th gate",
                "sequence": None,
                "needs": "",
            },
            14: {
                "address": "wa4_14",
                "description": "Sammer's Endgame, map of the 89th gate",
                "sequence": None,
                "needs": "",
            },
            15: {
                "address": "wa4_15",
                "description": "Sammer's Endgame, map of the 90th gate",
                "sequence": None,
                "needs": "",
            },
            16: {
                "address": "wa4_16",
                "description": "Sammer's Endgame, map of the 91th gate",
                "sequence": None,
                "needs": "",
            },
            17: {
                "address": "wa4_17",
                "description": "Sammer's Endgame, map of the 92th gate",
                "sequence": None,
                "needs": "",
            },
            18: {
                "address": "wa4_18",
                "description": "Sammer's Endgame, map of the 93th gate",
                "sequence": None,
                "needs": "",
            },
            19: {
                "address": "wa4_19",
                "description": "Sammer's Endgame, map of the 94th gate",
                "sequence": None,
                "needs": "",
            },
            20: {
                "address": "wa4_20",
                "description": "Sammer's Endgame, map of the 95th gate",
                "sequence": None,
                "needs": "",
            },
            21: {
                "address": "wa4_21",
                "description": "Sammer's Endgame, map of the 96th gate",
                "sequence": None,
                "needs": "",
            },
            22: {
                "address": "wa4_22",
                "description": "Sammer's Endgame, map of the 97th gate",
                "sequence": None,
                "needs": "",
            },
            23: {
                "address": "wa4_23",
                "description": "Sammer's Endgame, map of the 98th gate",
                "sequence": None,
                "needs": "",
            },
            24: {
                "address": "wa4_24",
                "description": "Sammer's Endgame, map of the 99th gate",
                "sequence": None,
                "needs": "",
            },
            25: {
                "address": "wa4_25",
                "description": "Sammer's Endgame, map of the 100th gate",
                "sequence": None,
                "needs": "",
            },
            26: {
                "address": "wa4_26",
                "description": "Sammer's Endgame, map with the Star Block",
                "sequence": None,
                "needs": "",
            },
        },
    },
    7: {
        1: {
            1: {
                "address": "an1_01",
                "description": "The Underwhere, map with the healing fountain",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "an1_02",
                "description": "The Underwhere, map with the two floors",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "an1_03",
                "description": "The Underwhere, map with the River Twigg surface",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "an1_04",
                "description": "The Underwhere, map with the iron floor (rightmost map of the chapter)",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "an1_05",
                "description": "The Underwhere, map with the Star Block",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "an1_06",
                "description": "The Underwhere, sewers at the bottom of River Twigg",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "an1_07",
                "description": "The Underwhere, map with the three orange spout",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "an1_08",
                "description": "The Underwhere, map with only pipes (the map you go to meet Luvbi after getting Luigi)",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "an1_09",
                "description": "The Underwhere, underground map with blocks",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "an1_00",
                "description": "The Underwhere, underground map with a blue switch",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "an1_01",
                "description": "The Underwhere, underground map with a Gigabite",
                "sequence": None,
                "needs": "",
            },
        },
        2: {
            1: {
                "address": "an2_01",
                "description": "Underwhere Road, corridor with a door on the right",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "an2_02",
                "description": "Underwhere Road, dark map with Dorguy The First",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "an2_03",
                "description": "Underwhere Road, corridor with three door and a save block",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "an2_04",
                "description": "Underwhere Road, dark map with a door on the left",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "an2_05",
                "description": "Underwhere Road, dark map with Dorguy The Second",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "an2_06",
                "description": "Underwhere Road, corridor with the red door",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "an2_07",
                "description": "Underwhere Road, map with the three sisters",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "an2_08",
                "description": "Underwhere Road, dark map with Dorguy The Third",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "an2_09",
                "description": "Underwhere Road, map with the Star Block",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "an2_10",
                "description": "Underwhere Road, underground map with coins",
                "sequence": None,
                "needs": "",
            },
        },
        3: {
            1: {
                "address": "an3_01",
                "description": "Overthere Stair, Stair 1",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "an3_02",
                "description": "Overthere Stair, Stair 4 (map with a save block near a door)",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "an3_03",
                "description": "Overthere Stair, Stair 5",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "an3_04",
                "description": "Overthere Stair, map with Star Block",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "an3_05",
                "description": "Overthere Stair, map with Blue Apples tree",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "an3_06",
                "description": "Overthere Stair, map with the Gold Apple tree",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "an3_07",
                "description": "Overthere Stair, map with Yellow Apples tree",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "an3_08",
                "description": "Overthere Stair, map with Red Apples tree",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "an3_09",
                "description": "Overthere Stair, map with Pink Apples tree",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "an3_10",
                "description": "Overthere Stair, map with Black Apples tree",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "an3_11",
                "description": "Overthere Stair, map with Skellobits",
                "sequence": None,
                "needs": "",
            },
            12: {
                "address": "an3_12",
                "description": "Overthere Stair, Stair 2",
                "sequence": None,
                "needs": "",
            },
            13: {
                "address": "an3_13",
                "description": "Overthere Stair, Stair 3",
                "sequence": None,
                "needs": "",
            },
            14: {
                "address": "an3_14",
                "description": "Overthere Stair, Stair 6",
                "sequence": None,
                "needs": "",
            },
            15: {
                "address": "an3_15",
                "description": "Overthere Stair, Stair 7 (map with Cyrrus)",
                "sequence": None,
                "needs": "",
            },
            16: {
                "address": "an3_16",
                "description": "Overthere Stair, map with the planet Earth (loads the cutscene of being launched into space upon loading)",
                "sequence": None,
                "needs": "",
            },
        },
        4: {
            1: {
                "address": "an4_01",
                "description": "The Overthere, sector 1",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "an4_02",
                "description": "The Overthere, sector 3 (map with Overvator and a save block)",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "an4_03",
                "description": "The Overthere, sector 4 (map with rainbow bridge)",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "an4_04",
                "description": "The Overthere, sector 2 (map with Blubi)",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "an4_05",
                "description": "The Overthere, sector 5 (map with a platform controlled by a red block switch)",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "an4_06",
                "description": "The Overthere, sector 6 (map with Yebbi)",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "an4_07",
                "description": "The Overthere, sector 7 (map with Rebbi)",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "an4_08",
                "description": "The Overthere, sector 8",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "an4_09",
                "description": "The Overthere, map with stairs and a save block near a door",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "an4_10",
                "description": "The Overthere, map with Star Block",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "an4_11",
                "description": "The Overthere, map with a Gigabite",
                "sequence": None,
                "needs": "",
            },
            12: {
                "address": "an4_12",
                "description": "The Overthere, map with coins and two treasure chests",
                "sequence": None,
                "needs": "",
            },
        },
    },
    8: {
        1: {
            1: {
                "address": "ls1_01",
                "description": "Castle Bleck Entry, castle entrance",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "ls1_02",
                "description": "Castle Bleck Entry, map with a big door on the left",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "ls1_03",
                "description": "Castle Bleck Entry, map with three doors and two staircases",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "ls1_04",
                "description": "Castle Bleck Entry, map outside the castle with a dead end on the left",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "ls1_05",
                "description": "Castle Bleck Entry, map with three doors and a platform in the air",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "ls1_06",
                "description": "Castle Bleck Entry, map outside the castle with a pipe",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "ls1_07",
                "description": "Castle Bleck Entry, map with a small corridor and a treasure chest",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "ls1_08",
                "description": "Castle Bleck Entry, map with corridor and a lot of enemies",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "ls1_09",
                "description": "Castle Bleck Entry, map with fire torches",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "ls1_10",
                "description": "Castle Bleck Entry, map with huge staircase",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "ls1_11",
                "description": "Castle Bleck Entry, O'Chunks fight map",
                "sequence": None,
                "needs": "",
            },
            12: {
                "address": "ls1_12",
                "description": "Castle Bleck Entry, map with Star Block",
                "sequence": None,
                "needs": "",
            },
        },
        2: {
            1: {
                "address": "ls2_01",
                "description": "Castle Bleck Foyer, first map",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "ls2_02",
                "description": "Castle Bleck Foyer, map with 3 treasure chests above the ceiling",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "ls2_03",
                "description": "Castle Bleck Foyer, map with the prison cell",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "ls2_04",
                "description": "Castle Bleck Foyer, map with firebars and a red switch block",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "ls2_05",
                "description": "Castle Bleck Foyer, map with spikes and a red switch block",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "ls2_06",
                "description": "Castle Bleck Foyer, map with five pipes",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "ls2_07",
                "description": "Castle Bleck Foyer, map with three doors and 2 staircases",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "ls2_08",
                "description": "Castle Bleck Foyer, map with three Cursya outside of the castle",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "ls2_09",
                "description": "Castle Bleck Foyer, map with suspended Mushrooms",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "ls2_10",
                "description": "Castle Bleck Foyer, map with three Shlorp",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "ls2_11",
                "description": "Castle Bleck Foyer, map with three Cherbil",
                "sequence": None,
                "needs": "",
            },
            12: {
                "address": "ls2_12",
                "description": "Castle Bleck Foyer, map with Chromeba",
                "sequence": None,
                "needs": "",
            },
            13: {
                "address": "ls2_13",
                "description": "Castle Bleck Foyer, map with small room and two doors",
                "sequence": None,
                "needs": "",
            },
            14: {
                "address": "ls2_14",
                "description": "Castle Bleck Foyer, first hated thing room",
                "sequence": None,
                "needs": "",
            },
            15: {
                "address": "ls2_15",
                "description": "Castle Bleck Foyer, second hated thing room",
                "sequence": None,
                "needs": "",
            },
            16: {
                "address": "ls2_16",
                "description": "Castle Bleck Foyer, third hated thing room",
                "sequence": None,
                "needs": "",
            },
            17: {
                "address": "ls2_17",
                "description": "Castle Bleck Foyer, Mimi fight map",
                "sequence": None,
                "needs": "",
            },
            18: {
                "address": "ls2_18",
                "description": "Castle Bleck Foyer, map with Star Block",
                "sequence": None,
                "needs": "",
            },
        },
        3: {
            1: {
                "address": "ls3_01",
                "description": "Castle Bleck Interior, first map",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "ls3_02",
                "description": "Castle Bleck Interior, map with Hogarithm and two doors",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "ls3_03",
                "description": "Castle Bleck Interior, first map with glass frames",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "ls3_04",
                "description": "Castle Bleck Interior, map with three doors and two staircases",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "ls3_05",
                "description": "Castle Bleck Interior, first map with three blocks",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "ls3_06",
                "description": "Castle Bleck Interior, second map with three blocks",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "ls3_07",
                "description": "Castle Bleck Interior, third map with three blocks",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "ls3_08",
                "description": "Castle Bleck Interior, map with three Red Chomp and a blue switch block",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "ls3_09",
                "description": "Castle Bleck Interior, fourth map with three blocks",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "ls3_10",
                "description": "Castle Bleck Interior, map with multiple platforms and two doors",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "ls3_11",
                "description": "Castle Bleck Interior, second map with glass frames",
                "sequence": None,
                "needs": "",
            },
            12: {
                "address": "ls3_12",
                "description": "Castle Bleck Interior, Dimentio fight map",
                "sequence": None,
                "needs": "",
            },
            13: {
                "address": "ls3_13",
                "description": "Castle Bleck Interior, map with Star Block",
                "sequence": None,
                "needs": "",
            },
        },
        4: {
            1: {
                "address": "ls4_01",
                "description": "Castle Bleck Inner Sanctum, first map",
                "sequence": None,
                "needs": "",
            },
            2: {
                "address": "ls4_02",
                "description": "UNUSED Castle Bleck Inner Sanctum,, large empty map with a door",
                "sequence": None,
                "needs": "",
            },
            3: {
                "address": "ls4_03",
                "description": "Castle Bleck Inner Sanctum, map with the pillar that goes up and down",
                "sequence": None,
                "needs": "",
            },
            4: {
                "address": "ls4_04",
                "description": "Castle Bleck Inner Sanctum, map with rectangular platforms elevators",
                "sequence": None,
                "needs": "",
            },
            5: {
                "address": "ls4_05",
                "description": "Castle Bleck Inner Sanctum, map with mini corridor and a treasure chest",
                "sequence": None,
                "needs": "",
            },
            6: {
                "address": "ls4_06",
                "description": "Castle Bleck Inner Sanctum, map with large corridor and a lot of enemies",
                "sequence": None,
                "needs": "",
            },
            7: {
                "address": "ls4_07",
                "description": "Castle Bleck Inner Sanctum, first map with labyrinth",
                "sequence": None,
                "needs": "",
            },
            8: {
                "address": "ls4_08",
                "description": "Castle Bleck Inner Sanctum, second map with labyrinth",
                "sequence": None,
                "needs": "",
            },
            9: {
                "address": "ls4_09",
                "description": "Castle Bleck Inner Sanctum, third map with labyrinth",
                "sequence": None,
                "needs": "",
            },
            10: {
                "address": "ls4_10",
                "description": "Castle Bleck Inner Sanctum, map with long staircase and a save block",
                "sequence": None,
                "needs": "",
            },
            11: {
                "address": "ls4_11",
                "description": "Castle Bleck Inner Sanctum, map with Star block",
                "sequence": None,
                "needs": "",
            },
            12: {
                "address": "ls4_12",
                "description": "Castle Bleck Inner Sanctum, wedding map",
                "sequence": None,
                "needs": "",
            },
            13: {
                "address": "ls4_13",
                "description": "Castle Bleck Inner Sanctum, map with small corridor and two doors",
                "sequence": None,
                "needs": "",
            },
        },
    },
    "misc": {},
}
